# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160610_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
