# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
